[package]
name = "wineforge-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Declarative, isolated Wine application launcher and prefix manager"
readme = "../../README.md"
keywords = ["wine", "windows", "macos", "linux", "launcher"]
categories = ["command-line-utilities", "emulators"]

[[bin]]
name = "wineforge"
path = "src/main.rs"

[[bin]]
name = "wineforge-launcher"
path = "src/launcher.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
flate2.workspace = true
icns.workspace = true
ico.workspace = true
pelite.workspace = true
regex.workspace = true
reqwest.workspace = true
roxmltree.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
toml.workspace = true
wineforge-core.workspace = true
zip.workspace = true

[dev-dependencies]
tempfile = "3.14"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"
disabled-strategies = ["quick-install"]
